coda-it/gowebapp

- Makefile
- client/app.scss
- client/modules/AlertPanel/_styles.scss
- client/modules/Application/Application.jsx
- client/modules/Application/__snapshots__/Application.test.jsx.snap
- package-lock.json
- package.json
- views/index.html
- views/main.html
- views/navigation.html
- views/view.html
**Business justification:** https://trello.com/c/V6dzqk0w/70-coda-70-cleanup-webapp-codebase
**Description:** Update graphen UI dependency.
> CODA-70 - Cleanup webapp UI

- Makefile
- client/app.scss
- client/modules/LoginBox/_styles.scss
- controllers/404.go
- controllers/login.go
- controllers/logout.go
- controllers/main.go
- controllers/register.go
- datasources/persistence/persistence.go
- datasources/types.go
- docker/webapp/dev/docker-compose.yml
- go.mod
- go.sum
- main.go
- models/page/page.go
- utils/render.go
- utils/session.go
- version.go
- views/login.html
- views/navigation.html
- views/register.html
**Business justification:** https://trello.com/c/aHLMiR7P/71-coda-71-add-login-mechanism
**Description:** Add login mechanism.
> CODA-71 - Add login mechanism

- .eslintrc
- client/modules/Admin/Admin.jsx
- package-lock.json
- package.json
- views/navigation.html
**Business justification:** https://trello.com/c/TFLOCY9L/76-coda-76-sub-menu
**Description:** Add submenu in the admin section.
> CODA-76 - Admin submenu

- client/app.jsx
- client/models/categories/actionTypes.js
- client/models/categories/actions.js
- client/models/categories/constants.js
- client/models/categories/reducers.js
- client/models/categories/sagas.js
- client/models/categories/selectors.js
- client/models/categories/types.js
- client/modules/Admin/Admin.jsx
- client/modules/Categories/Categories.jsx
- client/modules/Categories/index.jsx
- client/modules/Categories/types.js
- client/modules/CategoryEditor/CategoryEditor.jsx
- client/modules/CategoryEditor/index.jsx
- client/modules/CategoryEditor/types.js
- client/reducers.js
- client/sagas.js
- client/types.js
- controllers/api/category/delete.go
- controllers/api/category/get.go
- controllers/api/category/main.go
- controllers/api/category/post.go
- controllers/api/category/put.go
- cypress/integration/categories.spec.js
- main.go
- models/category/category.go
- models/category/constants.go
- models/category/data.go
- views/navigation.html
**Business justification:** https://trello.com/c/zttlJOd0/85-coda-85-add-category-section
**Description:** Add 'Category' section with CRUD operations.
> CODA-85 - Add 'Category' section

- client/app.jsx
- client/modules/Categories/Categories.jsx
- client/modules/Categories/index.jsx
- client/modules/Categories/types.js
- controllers/api/category/get.go
- controllers/api/post/get.go
- controllers/categories.go
- main.go
- models/category/data.go
- models/post/data.go
- utils/render.go
- views/categories.html
- views/navigation.html
**Business justification:** https://trello.com/c/edk9AwFb/80-coda-80-category-navigation
**Description:** Add `Category` section to the main navigation.
> CODA-80 - Category navigation

- client/models/posts/actions.js
- client/models/posts/sagas.js
- client/models/posts/types.js
- client/modules/PostEditor/PostEditor.jsx
- client/modules/PostEditor/index.jsx
- client/modules/PostEditor/types.js
- models/post/post.go
**Business justification:** https://trello.com/c/RpJ9QtAk/89-coda-89-native-category-dropdown-for-posts
**Description:** Add category field when adding a new post.
> CODA-89 - Native category dropdown for posts

- client/modules/Application/__snapshots__/Application.test.jsx.snap
- package-lock.json
- package.json
**Business justification:** https://trello.com/c/5NtrzEuK/104-coda-104-fix-css-linter
**Description:** Fix style linter paths to check `scss` files properly.
> CODA-104 - Fix css linter

- client/modules/Application/__snapshots__/Application.test.jsx.snap
- client/modules/Categories/Categories.jsx
- client/modules/Posts/Posts.jsx
- package-lock.json
- package.json
- views/login.html
- views/navigation.html
- views/register.html
**Business justification:** https://trello.com/c/g21nD7xq/107-coda-107-bump-graphen-version
**Description:** Bump `graphen` version and adopt layouting to the changes.
> CODA-107 - Bump graphen version

- client/app.jsx
- client/models/categories/selectors.js
- client/modules/Categories/Categories.jsx
- client/modules/Post/Post.jsx
- client/modules/Post/index.jsx
- client/modules/Post/types.js
- client/modules/Posts/Posts.jsx
- client/modules/Posts/index.jsx
- client/modules/Posts/types.js
- cypress/integration/posts.spec.js
- main.go
- views/navigation.html
**Business justification:** https://trello.com/c/Gn3qtPxu/106-coda-106-post-view
**Description:** Add post view.
> CODA-106 - Post view

- .travis.yml
- controllers/api/user/get.go
- controllers/register.go
- main.go
- models/page/page.go
- models/user/data.go
- models/user/user.go
- models/user/utils.go
- utils/render.go
- views/navigation.html
**Business justification:** https://trello.com/c/e8YbI9e2/91-coda-91-multiple-entitlement-levels
**Description:** Introduce a field for entitlements for users.
> CODA-91 - Multiple entitlement levels

- controllers/api/category/delete.go
- controllers/api/category/get.go
- controllers/api/category/post.go
- controllers/api/category/put.go
- controllers/api/post/delete.go
- controllers/api/post/get.go
- controllers/api/post/post.go
- controllers/api/post/put.go
- controllers/api/reset/post.go
- controllers/logout.go
- controllers/register.go
- utils/datasource.go
**Business justification:** https://trello.com/c/IRSmfhve/78-coda-78-data-source-assertion-cleanup
**Description:** Handle data assertion in one place for more consistent error handling and DRY code.
> CODA-78 - Data source assertion cleanup

- .travis.yml
- scripts/deploy.sh
**Business justification:** https://trello.com/c/6FI9xtl8/111-coda-111-deployment-integration
**Description:** Add deployment script.
> CODA-111 - Deployment integration

- README.md
**Business justification:** https://trello.com/c/MqnqrAJu/128-coda-128-update-reamemd
**Description:** Update `README.md` with instructions how to start development and gola of this project.
> CODA-128 - Update REAME.md

- controllers/api/login/controller.go
- controllers/api/login/options.go
- controllers/api/login/post.go
- controllers/api/user/get.go
- controllers/base/controller.go
- controllers/login/post.go
- domain/usecases/user/user.go
- main.go
**Business justification:** https://trello.com/c/zUBrNXvG/135-coda-135-mobile-user-login
**Description:** Add user login endpoint to api with CORS to handler mobile user login.
> CODA-135 - Mobile user login

- package-lock.json
- package.json
**Business justification:** https://trello.com/c/nyJJw9wR/140-coda-140-update-packages
**Description:** Update npm packages.
> CODA-140 - Update packages

- babel.config.js
- client/modules/Application/__snapshots__/Application.test.jsx.snap
- config/jest.config.js
- package-lock.json
- package.json
- webpack.dev.config.js
- webpack.prod.config.js
**Business justification:** https://trello.com/c/RAuMUTCP/141-coda-141-fix-hook-call-error
**Description:** Bump graphen version to import not minified bundle. Add module resolver in webpack to build properly. In order to interpret flow properly move from `.babelrc` (doesn't affect sub-packages) to `babel.config.j` (affects whole project).
> CODA-141 - Fix hook call error

- client/modules/PostEditor/PostEditor.jsx
- package-lock.json
- package.json
**Business justification**: https://trello.com/c/ZW92nIwF/126-coda-126-replace-native-dropdowns-with-graphen-ones
**Description**: Import dropdown from graphen and replace the old one in PostEditor component
> CODA-126 - Replace native dropdowns with graphen ones

- README.md
**Business justification:** https://trello.com/c/Kc0FvGGs/153-coda-153-skin-management
**Description:** Describe how front-end application should be customized.
> CODA-153 - Skin management

- client/models/users/selectors.ts
- client/modules/Application/index.ts
- client/modules/Application/selectors.ts
- client/modules/PostEditor/PostEditor.tsx
**Business justification:** https://trello.com/c/m5NGrt2T/148-coda-148-dropdown-refactor-and-fix
**Description:** Refactor and clean dropdown code
> CODA-148 - Dropdown refactor and fix

- cypress/integration/dropdown.spec.js
**Business justification:** https://trello.com/c/GBqmZsHN/162-coda-162-cover-dropdown-with-integration-tests
**Description:** Add integration tests to dropdown.
> CODA-162 - Cover dropdown with integration tests

- main.go
- webapp-config.json
**Business justification:** https://trello.com/c/tXnH6QsE/165-coda-165-landing-page
**Description:** Create new navigation link to landing page editor
> CODA-165 - Landing page

- data/config/config.go
- go.sum
**Business justification:** https://trello.com/c/KB3nzxvZ/185-coda-185-docker-webapp-config-param
**Description:** Add possibility to read `webapp-config.json` from custom paths.
> CODA-185 - Docker webapp-config param

- docker/webapp/prod/Dockerfile
**Business justification:** https://trello.com/c/zLhcn3ig/186-coda-186-docker-volume-dir
**Description:** Add one `volume` directory which can be mounted by administrator for various of purposes (ex. sharing external config).
> CODA-186 - Docker volume dir

- .travis.yml
- scripts/deploy.sh
**Business justification:** https://trello.com/c/xiQ84Zub/187-coda-187-binary-release
**Description:** Replace old dedicated deployment with release deployments.
> CODA-187 - Binary release

- .travis.yml
**Business justification:** https://trello.com/c/M9wlw0rJ/188-coda-remove-legacy-deployment
**Description:** Until successful release deployment is setup, legacy deployment and experimental versions should be removed.
> CODA-188 - Remove legacy deployment

- constants/config.go
- constants/modules.go
- controllers/base/controller.go
- controllers/landing/get.go
- controllers/static/controller.go
- controllers/static/get.go
- domain/models/platform/config.go
- main.go
- views/default/static.html
- webapp-config.json
**Business justification:** https://trello.com/c/qI6iFE2d/189-coda-189-static-layouts
**Description:** Add possibility to add simple landing static page layouts.
> CODA-189 - Static layouts

- controllers/api/platform/post.go
- controllers/api/platform/put.go
**Business justification:** https://trello.com/c/OmrC8KuI/190-coda-190-api-displays-posted-config
**Description:** When platform config is posted, return posted config.
> CODA-190 - API displays posted config

- controllers/api/platform/post.go
**Business justification:** https://trello.com/c/CiDX4re1/191-coda-191-return-config-id
**Description:** Create ID of created platform config.
> CODA-191 - Return config ID

- README.md
- controllers/api/platform/post.go
- docker/webapp/prod/Dockerfile
- views/default/view.html
- webpack.dev.config.js
- webpack.prod.config.js
**Business justification:** https://trello.com/c/6gevVUL9/192-coda-192-custom-apps-cleanup
**Description:** Cleanup code to make it easier to deploy custom apps on the platform.
> CODA-192 - Custom apps cleanup

- go.mod
- go.sum
- webapp-config.json
**Business justification:** https://trello.com/c/ytpXxyuF/195-coda-195-ssl-from-appconfig
**Description:** Add SSL configuration from `webapp-config.json` level.
> CODA-195 - SSL from appConfig

- client/config/index.ts
- client/models/config/types.ts
- client/utils/translations.ts
- constants/config.go
- controllers/base/controller.go
- controllers/landing/get.go
- controllers/static/get.go
- data/repositories/translation/translation.go
- domain/usecases/translation/interfaces.go
- domain/usecases/translation/translation.go
- go.mod
- go.sum
- main.go
- translations/en.json
- translations/pl.json
- views/default/static.html
- views/default/view.html
- webapp-config.json
**Business justification:** https://trello.com/c/nyakJqE3/220-coda-220-localization
**Description:** Add localization feature to the platform.
> CODA-220 - Localization

- docker/webapp/azure/docker-compose.yml
**Business justification:** https://trello.com/c/uB6lwAFC/157-coda-157-migration-to-appservice
**Description:** As the project is migrate to Azure AppServices, a deployment `docket-compose.yml` script is being added.
> CODA-157 - Migration to AppService

- .travis.yml
- docker/webapp/azure/docker-compose.yml
- docker/webapp/dev/docker-compose.yml
**Business justification:** https://trello.com/c/FIA2A0fa/257-coda-257-lock-mongo-version
**Description:** Lock mongodb version.
> CODA-257 - Lock mongo version

- client/app.tsx
- client/models/alerts/actions.ts
- client/models/categories/actions.ts
- client/models/helpdesk/actionTypes.ts
- client/models/helpdesk/actions.ts
- client/models/helpdesk/constants.ts
- client/models/helpdesk/reducers.ts
- client/models/helpdesk/sagas.ts
- client/models/helpdesk/selectors.ts
- client/models/helpdesk/types.ts
- client/modules/CategoryEditor/index.tsx
- client/modules/Helpdesk/Helpdesk.tsx
- client/modules/Helpdesk/index.ts
- client/modules/Helpdesk/types.ts
- client/reducers.ts
- client/sagas.ts
- client/types.ts
- client/utils/types.ts
- controllers/api/helpdesk/constants.go
- controllers/api/helpdesk/controller.go
- controllers/api/helpdesk/get.go
- controllers/api/helpdesk/post.go
- data/repositories/helpdesk/helpdesk.go
- domain/models/ticket/ticket.go
- domain/usecases/helpdesk/helpdesk.go
- domain/usecases/helpdesk/interfaces.go
- main.go
- webapp-config.json
**Business justification:** https://trello.com/c/jZ44tGPZ/265-coda-265-helpdesk-form
**Description:** Implement helpdesk module form.
> CODA-265 - Helpdesk form

- client/app.tsx
- client/modules/AlertPanel/Alert.tsx
- client/modules/Application/Application.tsx
- client/modules/Application/sagas.ts
- client/reducers.ts
- package-lock.json
- package.json
**Business justification:** https://trello.com/c/UX1AoLzo/272-coda-272-migration-redux-to-rtk
**Description:** Migrate Redux to Redux Tool Kit.
> CODA-272 - Migration Redux to RTK

- go.mod
- go.sum
- webapp-config.json
**Business justification:** https://trello.com/c/KPwa0YTt/274-coda-274-default-application-for-domain
**Description:** Every application may have assigned domain what will be accessed only with it.
> CODA-274 - Default application for domain

- .github/workflows/test.yml
- client/modules/AlertPanel/Alert.test.tsx
- client/modules/AlertPanel/AlertPanel.test.tsx
- client/modules/Application/Application.test.tsx
- package-lock.json
- package.json
- tsconfig.json
**Business requirement:** https://trello.com/c/xWsp0zer/282-coda-282-fix-linting-job
**Description:** Linting job was broken because TravisCI was inactive for long period of time. This PR fixes it.
> CODA-282 - Fix linting job

- controllers/base/controller.go
- docker/webapp/azure/docker-compose.yml
- go.mod
- go.sum
- main.go
**Business justification:** https://trello.com/c/uaj9olD2/289-coda-289-render-app-template-by-domain
**Description:** Render particular set of templated based on from which domain the request comes.
> CODA-289 - Render app template by domain

- docker/webapp/azure/docker-compose.yml
**Business justification:** https://trello.com/c/rf049Bhb/280-coda-280-views-template-storage
**Description:** Add to deployment file persistent file storage.
> CODA-280 - Views template storage

- controllers/api/platform/get.go
- data/repositories/platform/platfrom.go
- docker/webapp/azure/docker-compose.yml
**Business justification:** https://trello.com/c/wmIfUtwS/292-coda-292-platform-config-error-when-updating
**Description:** When updating the platform config an error occurs.
> CODA-292 - Platform config error when updating

- controllers/api/platform/get.go
- controllers/api/platform/post.go
- controllers/base/controller.go
- controllers/landing/get.go
- controllers/static/get.go
- data/repositories/platform/platfrom.go
- domain/models/platform/config.go
- domain/usecases/platform/interfaces.go
- domain/usecases/platform/platform.go
**Business justification:** https://trello.com/c/5Flsaryn/293-coda-293-app-settings-per-application
**Description:** Platform config should be kept by particular application ID.
> CODA-293 - App settings per application

- client/app.tsx
- client/models/helpdesk/actionTypes.ts
- client/models/helpdesk/actions.ts
- client/models/helpdesk/reducers.ts
- client/models/helpdesk/sagas.ts
- client/models/helpdesk/selectors.ts
- client/models/helpdesk/types.ts
- client/modules/HelpdeskAdmin/index.tsx
- client/sagas.ts
- controllers/api/helpdesk/get.go
- data/repositories/helpdesk/helpdesk.go
- domain/usecases/helpdesk/helpdesk.go
- domain/usecases/helpdesk/interfaces.go
- main.go
- webapp-config.json
**Business justification:** https://trello.com/c/Dw4a14Y2/296-coda-296-helpdesk-admin
**Description:** Administrator should have possibility to see list of created tickets.
> CODA-296 - Helpdesk admin

- client/models/helpdesk/actionTypes.ts
- client/models/helpdesk/actions.ts
- client/models/helpdesk/sagas.ts
- client/models/helpdesk/types.ts
- client/modules/HelpdeskAdmin/index.tsx
- client/sagas.ts
- controllers/api/helpdesk/delete.go
- data/repositories/helpdesk/helpdesk.go
- domain/usecases/helpdesk/helpdesk.go
- domain/usecases/helpdesk/interfaces.go
- main.go
**Business justification:** https://trello.com/c/5U5R2WVL/297-coda-297-helpdesk-ticket-removal
**Description:** Admin user should be able to remove helpdesk ticket.
> CODA-297 - Helpdesk ticket removal

- client/models/helpdesk/actionTypes.ts
- client/models/helpdesk/actions.ts
- client/models/helpdesk/constants.ts
- client/models/helpdesk/sagas.ts
- client/models/helpdesk/types.ts
- client/modules/HelpdeskAdmin/index.tsx
- client/modules/HelpdeskAdmin/ticket.tsx
- client/sagas.ts
- controllers/api/helpdesk/put.go
- cypress/plugins/index.js
- cypress/support/e2e.js
- data/repositories/helpdesk/helpdesk.go
- domain/models/ticket/ticket.go
- domain/usecases/helpdesk/helpdesk.go
- domain/usecases/helpdesk/interfaces.go
- main.go
**Business justification:** https://trello.com/c/wgcCkX25/298-coda-298-ticket-status
**Description:** Add ticket status to helpdesk tickets.
> CODA-298 - Ticket status

- go.mod
- go.sum
**Business justification:** https://trello.com/c/bjjZnTRD/300-coda-300-remove-unsafe-characters-from-ticket-hash
**Description:** Ticket hashes should be URL safe. New `goutils` version contains that fix.
> CODA-300 - Remove unsafe characters from ticket hash

- client/external.d.ts
- client/modules/HelpdeskAdmin/ticket.tsx
- cypress/e2e/categories.cy.js
- cypress/e2e/posts.cy.js
- package-lock.json
- package.json
**Business justification:** https://trello.com/c/luJ0gft0/305-coda-305-helpdesk-tickets-ui-ux
**Description:** Improve helpdesk admin UI/UX.
> CODA-305 - Helpdesk tickets UI/UX

- controllers/register/post.go
- data/repositories/user/user.go
- domain/usecases/user/interfaces.go
- domain/usecases/user/user.go
- go.mod
- go.sum
- main.go
**Business justification:** https://trello.com/c/9GnjnVDA/309-coda-309-user-activation-email
**Description:** When new user is being registered an activation email should be sent.
> CODA-309 - User activation email

- controllers/api/platform/get.go
- controllers/api/platform/post.go
- controllers/base/controller.go
- controllers/landing/get.go
- controllers/register/controller.go
- controllers/register/post.go
- controllers/static/get.go
- domain/usecases/platform/interfaces.go
- domain/usecases/platform/platform.go
- main.go
**Business justification:** https://trello.com/c/uc0uIRKU/311-coda-311-refactor-get-application-by-request
**Description:** Recognizing app by request occurs in many place, move it to usecases.
> CODA-311 - Refactor get application by request

- controllers/register/get.go
- controllers/register/post.go
- domain/usecases/user/user.go
- go.mod
- go.sum
- views/default/register.html
**Business justification:** https://trello.com/c/GnDKxAnW/308-coda-308-user-already-registered
**Description:** When user is already registered rise an error.
> CODA-308 - User already registered

- controllers/register/post.go
- go.mod
- go.sum
- main.go
**Business justification:** https://trello.com/c/APC0DZxp/314-coda-314-update-mailer
**Description:** Update mailer with `goutils`.
> CODA-314 - Update mailer

- main.go
**Business justification:** https://trello.com/c/FI508iQO/315-coda-315-fix-env-logs
**Description:** ENV variables for mailer has been changed but logs remained old and need to be adjusted.
> CODA-315 - Fix ENV logs

- docker/webapp/azure/docker-compose.yml
**Business justification:** https://trello.com/c/FpvSNmK2/316-coda-azure-compose-update
**Description:** Update docker compose file with mailer ENV variables.
> CODA-316 - Azure compose update

- client/app.tsx
- client/models/users/actionTypes.ts
- client/models/users/actions.ts
- client/models/users/sagas.ts
- client/modules/Account/index.tsx
- client/sagas.ts
- controllers/account/controller.go
- controllers/account/get.go
- controllers/api/user/delete.go
- cypress/e2e/loginPage.cy.js
- data/repositories/user/user.go
- domain/usecases/user/interfaces.go
- domain/usecases/user/user.go
- go.mod
- go.sum
- main.go
- views/default/account.html
- views/default/navigation.html
- webapp-config.json
**Business justification:** https://trello.com/c/YeaZhUoR/317-coda-317-account-deletion
**Description:** Users should have possibility to create account.
> CODA-317 - Account deletion

- client/components/Previewer/_styles.scss
- client/components/Previewer/index.tsx
- client/modules/Account/index.tsx
- client/modules/Admin/Admin.tsx
- client/modules/Categories/Categories.tsx
- client/modules/CategoryEditor/CategoryEditor.tsx
- client/modules/Helpdesk/Helpdesk.tsx
- client/modules/HelpdeskAdmin/ticket.tsx
- client/modules/PlatformEditor/PlatformEditor.tsx
- client/modules/Post/Post.tsx
- client/modules/PostEditor/PostEditor.tsx
- client/modules/Posts/Posts.tsx
- cypress/e2e/posts.cy.js
- package-lock.json
- package.json
**Business justification:** https://trello.com/c/FMvby3b9/321-coda-321-ui-micro-adjustments
**Description:** Introduce UI adjustments.
> CODA-321 - UI micro adjustments

- client/models/platform/types.ts
- client/modules/Categories/Categories.tsx
- client/modules/PlatformEditor/PlatformEditor.tsx
- client/modules/Posts/Posts.tsx
- client/utils/translations.ts
- constants/apps.go
- controllers/base/controller.go
- data/repositories/translation/translation.go
- domain/models/platform/config.go
- translations/pl.json
- views/default/navigation.html
**Business justification:** https://trello.com/c/xql4Z3Hf/323-coda-323-language-change
**Description:** Platform should support language translations in both front-end and back-end layouts.
> CODA-323 - Language change

- client/models/config/types.ts
- client/modules/PlatformEditor/PlatformEditor.tsx
- go.mod
- go.sum
- package-lock.json
- package.json
- webapp-config.json
**Business justification:** https://trello.com/c/DZiSHA6o/328-coda-328-language-dropdown
**Description:** Language selection should be based on dropdown instead of textbox.
> CODA-328 - Language dropdown

- docker/webapp/azure/docker-compose.yml
**Business justification:** https://trello.com/c/rsa9ltSB/329-coda-329-docker-translations-mount
**Description:** Mount translations folder.
> CODA-329 - Docker translations mount

- controllers/base/controller.go
**Business justification:** https://trello.com/c/aCp949gk/333-coda-initial-language-without-cookie
**Description:** When language cookie is not set, language should be selected based on platform configuration.
> CODA-333 - Initial language without cookie

- client/app.tsx
- client/models/translations/actionTypes.ts
- client/models/translations/actions.ts
- client/models/translations/constants.ts
- client/models/translations/reducers.ts
- client/models/translations/sagas.ts
- client/models/translations/selectors.ts
- client/models/translations/types.ts
- client/modules/Translations/EditTranslation.tsx
- client/modules/Translations/index.tsx
- client/reducers.ts
- client/sagas.ts
- client/types.ts
- controllers/api/translations/constants.go
- controllers/api/translations/controller.go
- controllers/api/translations/get.go
- controllers/api/translations/post.go
- controllers/api/translations/put.go
- controllers/base/controller.go
- controllers/translations/controller.go
- controllers/translations/get.go
- data/repositories/dynamictranslation/dynamictranslation.go
- domain/models/translation/translation.go
- domain/usecases/translation/interfaces.go
- domain/usecases/translation/translation.go
- main.go
- views/default/translations.html
- webapp-config.json
**Business justification:** https://trello.com/c/OJxErINT/337-coda-337-dynamic-translation-write
**Description:** Add possibility to write dynamic translations.
> CODA-337 - Dynamic translation

- client/models/translations/actionTypes.ts
- client/models/translations/actions.ts
- client/models/translations/sagas.ts
- client/models/translations/types.ts
- client/modules/Translations/EditTranslation.tsx
- client/sagas.ts
- controllers/api/translations/delete.go
- data/repositories/dynamictranslation/dynamictranslation.go
- domain/usecases/translation/interfaces.go
- domain/usecases/translation/translation.go
- main.go
**Business justification:** https://trello.com/c/IniVpy7H/338-coda-338
**Description:** User should have possibility to delete dynamic translations.
> CODA-338 - Dynamic translation deletion

- go.mod
- package-lock.json
- package.json
**Business justification:** https://trello.com/c/Jpsr0eir/341-coda-341-update-ts-ang-go-versions
**Description:** Update Go and TS versions.
> CODA-341 - Update TS and Go versions

- client/app.scss
- client/modules/Translations/EditTranslation.tsx
- client/modules/Translations/_styles.scss
- client/modules/Translations/index.tsx
**Business justification:** https://trello.com/c/9PUMkipB/343-coda-343-enhance-translations-panel
**Description:** Enhance translation UI to be more accessible for users.
> CODA-343 - Enhance translations panel

- client/modules/Translations/EditTranslation.tsx
- package-lock.json
- package.json
**Business justification:** https://trello.com/c/UZHxNQ7v/346-coda-346-disabled-language-dropdown-in-read-mode
**Description:** When translations are in read-only state, language should not be available for selection.
> CODA-346 - Disabled language dropdown in read-mode

- client/models/platform/types.ts
- client/modules/PlatformEditor/PlatformEditor.tsx
- controllers/login/controller.go
- controllers/login/post.go
- domain/models/platform/config.go
- main.go
**Business justification:** https://trello.com/c/vURSsjox/345-coda-345-languages-in-posts
**Description:** Allow users to set custom login redirect URL.
> CODA-345 - Customizable login redirect URL

- client/modules/PlatformEditor/PlatformEditor.tsx
- client/modules/Translations/EditTranslation.tsx
- client/modules/Translations/_styles.scss
- controllers/static/get.go
- package-lock.json
- package.json
**Business justification:** https://trello.com/c/n9hiYLRy/349-coda-text-area-as-translation-value
**Description:** Translation value should be textarea instead of text input. This change also introduce few minor cleanups.
> CODA-349 - Text area as translation value

- client/modules/PlatformEditor/PlatformEditor.tsx
**Business justification:** https://trello.com/c/Bm52hvKG/350-coda-landing-page-as-dropdown
**Description:** Landing page as input text field is not easy to use for users it should be accessible as a dropdown.
> CODA-350 - Landing page as dropdown
